### ISSUE TITLE
Sidebar cannot be scrolled to the end when menu items overflow screen size

### ISSUE THREAD

**Issue by nyerslaszlo** [creativetimofficial/ct-black-dashboard-pro-laravel#1]
This problem can be seen on the live demo as well as on the downloaded version.
Tested in Google Chrome (latest as of now) and Firefox.

[Picture](https://i.imgur.com/f9Z5pqL.png)

Not a huge problem, but would be nice if it would be fixed.

**Comment by teamupdivision** [comment]
Hello @nyerslaszlo, thanks for using our products.
Can you please let me know exactly what is the problem, I could not identify it from the screenshot.

Thank you

**Comment by nyerslaszlo** [comment]
Hello, sorry I wrote the problem into the title:

The sidebar cannot be scrolled to the end when menu items overflow screen size.

As shown on the screenshot the "charts" and the "calendar" menu items at the bottom of the sidebar cannot be seen properly, and you can not scroll down further.

Thank you for your time!

**Comment by teamupdivision** [comment]
Hello @nyerslaszlo, thanks for using Creative Tim products!
We've made a temporary update and disabled the custom scrollbar. Please check it out.

All the best

**Comment by nyerslaszlo** [comment]
Hi @teamupdivision. Yes, using the default scrollbar seems to fix the problem. It breaks the design a little bit, but it's a good temporary solution. Thank you!
