### ISSUE TITLE
Internal Server Error The server encountered... after install and trying to login for first time

### ISSUE THREAD

**Issue by marcqvn** [creativetimofficial/ct-black-dashboard-pro-laravel#11]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] Laravel 7.2.0
- [X] PHP 7.4
- [X] MySQL version: 5.7
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

After installation according documentation, error message 

"_Internal Server Error The server encountered an internal error or misconfiguration and was unable to complete your request..._"

is displayed when trying to access the dashboard login page :

https://commandes-mage.patisseriemage.ch/login

# Current Behavior

What is the current behavior?

Can't access the login page.

# Failure Information (for bugs)

I don't know if it is a bug or not.
I have checked my env file and all information are correct. 
No log file generated in storage/logs. 
Dashboard is installed in a subdomain. I have 2 other Laravel applications which are installed in two other subdomains and I had no issues. I had no issues by installing Laravel and Crudbooster and accessing the login page. So I can't explain why this error. Files are installed in the project folder subdomain of web folder. Database is populated with the tables and data. env. file and particularly the database and database connection information are correct... Database and user permissions are correct.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. I have followed the Laravel setup according your documentation without missing one point.
2. I passed the url "https://commandes-mage.patisseriemage.ch/login" in order to access the login page.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: PC
* Operating System: Windows 10
* Browser and Version: Chrome : tested on the 2 following browsers : Version 84.0.4147.125 (Official Build) (64-bit), Opera : Version:69.0.3686.95

* Host: by Infomaniak, Geneva, Switzerland
Dns, type A for commandes-mage.patisseriemage.ch was tested and is approved and correct

## Failure Logs

No log generated in storage/logs. 
Server error log for subdomain in attachment (commandes-mage.patisseriemage.ch-2020-08-18_15-55-36-error.log)

Hi,

I would appreciate if you could tell me how I can solve this issue, since I'm stuck.

Thank you in advance, cheers,

Marc

Screen captures and files
![image](https://user-images.githubusercontent.com/69787855/90372823-36132b00-e09b-11ea-91d4-5f157d6e8a2a.png)
![image](https://user-images.githubusercontent.com/69787855/90372344-77570b00-e09a-11ea-8c7b-61fe457328ee.png)
![image](https://user-images.githubusercontent.com/69787855/90372369-82aa3680-e09a-11ea-9b87-eae8584d8165.png)
![image](https://user-images.githubusercontent.com/69787855/90372395-8d64cb80-e09a-11ea-8365-b9eb7a9d9ecf.png)
![image](https://user-images.githubusercontent.com/69787855/90372553-c3a24b00-e09a-11ea-830e-66a870cc2c88.png)
[PHPACTIVATEDEXTENSIONS.docx](https://github.com/creativetimofficial/ct-black-dashboard-pro-laravel/files/5082933/PHPACTIVATEDEXTENSIONS.docx)
[PHP INFORMATION.docx](https://github.com/creativetimofficial/ct-black-dashboard-pro-laravel/files/5082940/PHP.INFORMATION.docx)
[ENVFILE.docx](https://github.com/creativetimofficial/ct-black-dashboard-pro-laravel/files/5083329/ENVFILE.docx)
[commandes-mage.patisseriemage.ch-2020-08-18_15-55-36-error.log](https://github.com/creativetimofficial/ct-black-dashboard-pro-laravel/files/5089358/commandes-mage.patisseriemage.ch-2020-08-18_15-55-36-error.log)

**Comment by mariusconstantin2503** [comment]
Hi ,

It seems to be something wrong with your server configuration because there isn't anything into storage logs. Can you check if the domain points to the public folder? Have you added extra rules into your .htaccess file?

**Comment by marcqvn** [comment]
@mariusconstantin2503 

Hi,
Thank you for you reply.
No I haven't done any change in the .htaccess file.
Concerning the domain pointing to the public folder, I have installed the dashboard into a subdomain. 
What do you mean with the domain pointing to the public folder ? I have 2 other laravel apps which are as your dasboard installed into subdomains (web/app1, web/app2,web/commandes-mage.patisseriemage.ch), they are working fine, and I didn't needed to point anything to the public folder...

**Comment by marcqvn** [comment]
@mariusconstantin2503

I could fix it, I forgot to add an .htaccess into the root with among other the following 2 lines to point to the public folder :

    RewriteCond %{REQUEST_URI} !^/public/
    RewriteRule ^(.*)$ /public/$1 [L,QSA]

Sorry to have bothered you...

Cheers,

Marc

**Comment by teamupdivision** [comment]
Hi @marcqvn.

No problem.
We're glad you got to solve the problem.

All the best
