### ISSUE TITLE
Localization | Language : How do we handle | add other languages

### ISSUE THREAD

**Issue by marcqvn** [creativetimofficial/ct-black-dashboard-pro-laravel#12]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Ability to add languages in case of multilingual solutions. What would you suggest for your dashboard ?

# Current Behavior

Only English

# Failure Information (for bugs)

It is not a bug.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

Nothing to reproduce, only a question

## Context

No context necessary

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by marcq64** [comment]
Thank you for your support, great !!!
