### ISSUE TITLE
Role | Permissions : How do we handle it ? With Spatie or else ?

### ISSUE THREAD

**Issue by marcqvn** [creativetimofficial/ct-black-dashboard-pro-laravel#13]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Just would like to know how to handel roles and permissions, there's no information available. What would you suggest for your dashboard ?

I tried to add this 

`
          @if (Auth::user()->hasRole('Admin'))
  			
          <p>
          	Test Navbar Role 2 Admin
          </p>
          @endif
`

into your navbar view in order to filter what should be displayed according to given role.

Method App\User::hasRole() is undefined, so I guess I need to install the spatie package in order to handel roles and permissions, right ?

# Current Behavior

No roles and permissions management, it seems...

# Failure Information (for bugs)

No bug.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

No step to reproduce

If there's no information available into the dashboard documentation about Roles and Permissions and how to handel it (same for Localization and languages), I would suggest you could give users some details on how to handel it.

Thanks and cheers, Marc

**Comment by mariusconstantin2503** [comment]
Hi,
We use gates and policies to implement role restrictions. You can extend implemented policies and gates or you can install spatie package in order to use hasRole function. If you want to install spatie package you should remove all theme policies and gates and do all code changes required by spatie package.

**Comment by marcqvn** [comment]
Hi,
Cool, understood! Thank you for the explanation. Cheers, Marc
