### ISSUE TITLE
Modify Table Components

### ISSUE THREAD

**Issue by marcq64** [creativetimofficial/ct-black-dashboard-pro-laravel#14]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Just would like to make some change on tables components

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

**How can I make modifications those displayed components of the dashboard tables : 

Show X entries | Search field

Showing 1 to 50 of 78 entries

FIRST PREVIOUS NEXT LAST

I can't find the files related to those components. Would appreciate your support. Thanks.**

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by teamupdivision** [comment]
Hi @marcq64 

You can find a demo of this table in the installed project in Menu->Tables->DataTables.net .
The path of this page where you can find the code is : your-project folder/resources/views/pages/tables/tables_datatable.blade.php
For extra information about datatable, you can search in this documentation: https://datatables.net/

All the best

**Comment by marcq64** [comment]
Hi @teamupdivision

Cool ! Thanks for pointing me in the right direction, appreciated, already fixed, cheers, pa
