### ISSUE TITLE
sidebar.blade | ul/li systematically display bullet points | Impossible to disable the bullet points on ul / li

### ISSUE THREAD

**Issue by marcqvn** [creativetimofficial/ct-black-dashboard-pro-laravel#15]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version -> **I haven't installed Laravel 8 so version is the one for Laravel 7**
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
No bullet point added to li for sidebar.blade
I tried to add
list-style-type:none !important;
to
ul or li class
in
black-dashboard.css
cleared the cache, but no change, still systematically the bullets points
Please describe the behavior you are expecting
No bullet points added to ul / li for sidebar.blade
# Current Behavior
What is the current behavior?
bullets points are added to ul / li
# Failure Information (for bugs)
Don't know if it is a bug or not, I suppose no bullet points is displayed...
![image_2020-10-07_131806](https://user-images.githubusercontent.com/69787855/95294473-89397b00-089f-11eb-8fee-8467284d7437.png)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: PC Windows
* Operating System: windows 10
* Browser and Version: latest opera, chrome

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by rarestoma** [comment]
Hi @marcqvn,

Thank you for working with our products.

The bullet list are part of the black dashboard design and they are visible on the active elements. If you want to remove it you have to remove the following code from css:

```
.sidebar .nav li.active>a[data-toggle="collapse"]+div .nav .active a:before, 
.off-canvas-sidebar .nav li.active>a[data-toggle="collapse"]+div .nav .active a:before {
    content: " ";
    position: absolute;
    height: 6px;
    width: 6px;
    top: 17px;
    left: -4px;
    background: #ffffff;
    border-radius: 50%;
}
```

Please let me know if it works.

Thank you,
Rares

**Comment by marcqvn** [comment]
@rarestoma

Hi Rares,

Thank you for your prompt reply, appreciated... 
Your solution wasn't working, but it is working by disabling a little bit more of code (see below), just a few lines following the code your told me to disable.
So thank you for your support, which helped me to solve this issue.
Take care, cheers,
Marc


`.sidebar .nav li.active>a[data-toggle="collapse"]+div .nav .active a:before,
.off-canvas-sidebar .nav li.active>a[data-toggle="collapse"]+div .nav .active a:before {
  content: " ";
  position: absolute;
  height: 6px;
  width: 6px;
  top: 17px;
  left: -4px;
  background: #ffffff;
  border-radius: 50%;
}

.sidebar .nav li.active>a[data-toggle="collapse"]:before,
.off-canvas-sidebar .nav li.active>a[data-toggle="collapse"]:before {
  content: " ";
  position: absolute;
  height: 6px;
  width: 6px;
  top: 22px;
  left: -4px;
  background: rgba(255, 255, 255, 0.6);
  border-radius: 50%;`
