### ISSUE TITLE
eonasdan Datetimepicker doesn't display the date stored into the table, instead display the datetimepicker default value

### ISSUE THREAD

**Issue by marcqvn** [creativetimofficial/ct-black-dashboard-pro-laravel#18]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

Date saved into the database table should be displayed into the input field and not the default date of the datetimepicker

# Current Behavior

What is the current behavior?
The default date of the datetimepicker is displayed while editing a record and not the value of the datetimepicker stored into the table.

Thank you in advance for your support.

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.
Don't know if it is a bug

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: Laptop
* Operating System: Windows 10
* Browser and Version: All new version of Edge, Opera, Chrome etc.

## Failure Logs

Please include any relevant log snippets or files here.
HTML
<div class="form-group">
<input type="text" value="{{ $orderItem->delivery_date }}" name="delivery_date"  id="delivery_date" class="form-control datetimepicker">
</div>

JS

            $('.datetimepicker').datetimepicker({
                
                locale: 'fr',
                format : 'L',
                daysOfWeekDisabled: [0, 6],
                icons: {
                  time: "tim-icons icon-watch-time",
                  date: "tim-icons icon-calendar-60",
                  up: "fa fa-chevron-up",
                  down: "fa fa-chevron-down",
                  previous: 'tim-icons icon-minimal-left',
                  next: 'tim-icons icon-minimal-right',
                  today: 'fa fa-screenshot',
                  clear: 'fa fa-trash',
                  close: 'fa fa-remove'
                }
            });

You can see that the value displayed in the date field element is the date of the default datetimepicker plugin and not the date stored into the database table. Even if you can see the value into the value attribute of the html input tag.
![image](https://user-images.githubusercontent.com/69787855/202835932-f665a16d-a74e-4ac1-babd-57b9e2719691.png)
![image](https://user-images.githubusercontent.com/69787855/202835961-97763f40-d85a-4cf4-a016-aa1cbbbda503.png)

**Comment by teamupdivision** [comment]
Hello, 

Thank you for using Creative TIM products. 

Did you make sure to follow the examples we gave? You can see them in the folders below. 

app/Http/Controllers/ItemController.php
app/Item.php
app/Http/Requests/ItemRequest.php
app/Observers/ItemObserver.php
app/Policies/ItemPolicy.php
database/migrations/2019_01_21_163402_create_items_table.php
database/migrations/2019_03_06_143255_add_fields_to_items_table.php
database/seeds/ItemsTableSeeder.php
 

Also could you please send us the Model, Controller, Request and Blade files? 

Thank you.
