### ISSUE TITLE
Nothing configured for front-end build

### ISSUE THREAD

**Issue by ExcellentSP** [creativetimofficial/ct-black-dashboard-pro-laravel#6]
The docs state that gulp is the front-end build tool we should be using, but it's not preconfigured for the project. The `webpack.mix.js` file exists in the project, but it's not configured. What is the actual path for building and watching the front-end changes?

The docs also specify an "assets" directory but none exists.

**Comment by teamupdivision** [comment]
Hello @ExcellentSP, thank you for using our products.
You don't need to use the a build tool for frontend assets for the Laravel project install, use the frontend files "as is" and the project will work.

I will follow up on the assets folder issue.

I will close the other issues linked to gulp

Thank you

**Comment by Wildindfw** [comment]
I'm also curious, can you show a example of this?  I'm trying to link the new vue tailwinds version but cannot find any docs on how to properly do so with your themes. I have two pro purchases. Never used support

**Comment by rarestoma** [comment]
Hi @Wildindfw,

Thank you for your interest in our products.

We just launched a tailwind starter kit (https://www.creative-tim.com/learning-lab/tailwind-starter-kit#/presentation). It provides a lot of examples and complex documentation for a tailwind project.

What products did you try to integrate with vue tailwind?

Thank you,
Rares

**Comment by Wildindfw** [comment]
I'm new to code, I would just like a example of lets say the new tailwind vue with a laravel black dashboard.
