### ISSUE TITLE
Configure default settings

### ISSUE THREAD

**Issue by gh-zit** [creativetimofficial/ct-black-dashboard-pro-laravel#7]
We would like to remove the settings gear icon and instead set the color scheme default to blue and minimized sidebar. Cant find how to configure default settings in the documentations. Just like your Black React Dashboard: https://www.creative-tim.com/product/black-dashboard-pro-react

**Comment by eugentudorache** [comment]
Hello and thank you for using our products.
We do not have such settings on the Laravel project. Fastest way to remove those functionalities is:

1. to remove gear icon all together

2. hardcode to the color you want, see "orange" in my example
![image](https://user-images.githubusercontent.com/12085872/81315001-6c9bdb80-9092-11ea-8612-a5b0cfda470a.png)

3. hardcode the mini sidebar like in the image below
![image](https://user-images.githubusercontent.com/12085872/81315264-c6040a80-9092-11ea-9507-ca87935128fd.png)

**Comment by gh-zit** [comment]
Thanks for your swift reply.
I think your answer on #1 got lost.
