### ISSUE TITLE
No custom scrollbars

### ISSUE THREAD

**Issue by gh-zit** [creativetimofficial/ct-black-dashboard-pro-laravel#8]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed
- [x ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Custom scrollbars in widgets

![image](https://user-images.githubusercontent.com/64967641/81305546-c09cc500-907e-11ea-9457-3b9439a9f16d.png)

# Current Behavior

Browser default scroolbars and added horizontal scrollbars

![image](https://user-images.githubusercontent.com/64967641/81305467-a662e700-907e-11ea-9707-d55d7692e342.png)

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: Computer
* Operating System: Windows 10 Pro
* Browser and Version:  Google Chrome 81.0.4044.138

**Comment by teamupdivision** [comment]
Hello and thank you for using our products.
We'll be back with fix soon.
Thank you

**Comment by teamupdivision** [comment]
Hey, we fixed the issue we updated the download product archive.
You can also see it live in action here: https://www.creative-tim.com/live/black-dashboard-pro-laravel

All the best
