### ISSUE TITLE
Add custom field to user

### ISSUE THREAD

**Issue by gh-zit** [creativetimofficial/ct-black-dashboard-pro-laravel#9]
Could you please provide an example of how I could add a custom field to a user.
For example Phone number., I know how to add the field to the views files, but what files do I need to edit in the app folder. Also should i just create the column in phpmyadmin or use artisan?

Thanks in advance

**Comment by teamupdivision** [comment]
Hello,

You can edit the migration in path : "database/migrations/2019_01_15_110000_create_users_table.php" for example, and add to Schema of your database $table->string('number');

After that, you must to add this field ('number') in model ("app/User.php"), in this array: protected $fillable = []. 

Then run the "php artisan migrate:fresh" to make the changes in database.

All the best
